### PR TITLE
added editor_cmd in config.rs

### PR DESCRIPTION
**Pull request by Absobel**
and defaulted it to the env variable EDITOR and vi if not set

Okay this is actually my first pull request for a open source project ever, tell me if I'm doing things wrong

I tested this on my machine and it worked
I don't know if I have to add unit tests for that though

### CODE REVIEW

**Review by dzfrias — APPROVED** [review]
Looks great!

**Comment by Absobel** [comment]
Forgot to modify CONFIG.md though

**Comment by dzfrias** [comment]
That's good. We should wait to put it in CONFIG.md because the option won't work until a new release is out (unless they download from the main branch).

**Comment by Absobel** [comment]
Ah, I see :relieved:

**Pull request merged**
